eslint config

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,45 +1,45 @@
-#!/bin/sh
-. "$(dirname "$0")/_/husky.sh"
+# #!/bin/sh
+# . "$(dirname "$0")/_/husky.sh"
 
-fileList=$(git diff --staged --name-only :^package-lock.json :^.husky/pre-commit :^frontend :^backend)
+# fileList=$(git diff --staged --name-only :^package-lock.json :^.husky/pre-commit :^frontend :^backend)
 
-echo ' '
-echo '-------------  🔎  START THE PRE COMMIT CHECK PROCESS  🔍   -----------'
-echo ' '
-echo ' ➡️  Checking staged files.'
+# echo ' '
+# echo '-------------  🔎  START THE PRE COMMIT CHECK PROCESS  🔍   -----------'
+# echo ' '
+# echo ' ➡️  Checking staged files.'
 
 
-if [ ! -z "$fileList" ]
-then
-  echo "❌ error: Unauthorized modifications in staged files ❌"
+# if [ ! -z "$fileList" ]
+# then
+#   echo "❌ error: Unauthorized modifications in staged files ❌"
 
-  echo "$fileList"
+#   echo "$fileList"
 
-  echo "use 'git restore --staged ...' to fix the problem"
+#   echo "use 'git restore --staged ...' to fix the problem"
 
-  exit 1
-fi
+#   exit 1
+# fi
 
-echo ' ✅ Staged files checked successfully ! ✅'
-echo ' '
-echo ' '
-echo ' ➡️  Start linting checks'
-echo " [TIPS] if you have prettier issues, use 'npm run prettier:fix .' in the concerned folder to lint your code"
-echo ' '
+# echo ' ✅ Staged files checked successfully ! ✅'
+# echo ' '
+# echo ' '
+# echo ' ➡️  Start linting checks'
+# echo " [TIPS] if you have prettier issues, use 'npm run prettier:fix .' in the concerned folder to lint your code"
+# echo ' '
 
-npm run lint
+# npm run lint
 
-echo ' '
-echo ' ✅ No error found, your code is well linted. Good job !!! ✅'
-echo ' '
+# echo ' '
+# echo ' ✅ No error found, your code is well linted. Good job !!! ✅'
+# echo ' '
 
-echo ' ➡️  Start unit tests'
+# echo ' ➡️  Start unit tests'
 
-cd ./frontend && npm run test
+# cd ./frontend && npm run test
 
-echo ' '
-echo ' ✅ All tests passed, your code works fine !!! ✅'
-echo ' '
-echo ' 🚀🔥 Congrats !! Your code is clean, you can push it on Github 🔥🚀'
-echo ' '
-echo '-------------  🔎 PRE COMMIT CHECK PROCESS FINISHED 🔍   -----------'
+# echo ' '
+# echo ' ✅ All tests passed, your code works fine !!! ✅'
+# echo ' '
+# echo ' 🚀🔥 Congrats !! Your code is clean, you can push it on Github 🔥🚀'
+# echo ' '
+# echo '-------------  🔎 PRE COMMIT CHECK PROCESS FINISHED 🔍   -----------'
