test first commit with husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,24 +1,22 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-# fileList=$(git diff --staged --name-only :^package-lock.json :^README.md :^frontend :^backend)
+fileList=$(git diff --staged --name-only :^package-lock.json :^.husky/pre-commit :^frontend :^backend)
 
-# echo '----- Checking Root...'
+echo '----- Checking Root...'
 
-# if [ ! -z "$fileList" ]
-# then
-#   echo "error: Unauthorized modifications\n"
+if [ ! -z "$fileList" ]
+then
+  echo "error: Unauthorized modifications\n"
 
-#   echo "$fileList\n"
+  echo "$fileList\n"
 
-#   echo "use 'git restore --staged ...' to fix the problem"
-#   echo "(and ask your instructor why you should not change these files)\n"
+  echo "use 'git restore --staged ...' to fix the problem"
 
-#   exit 1
-# fi
+  exit 1
+fi
 
-# echo '----- Done!'
+echo '----- Done!'
 
-echo '----- Checking Repository...'
 
 npm run lint
